import React from 'react';
import LocalizedStrings from 'react-native-localization';
const strings = new LocalizedStrings({
    "en": {
        CitiApp: "CitiApp",
        Sundsvalls_Kommun: "KRAMFORS",
        Log_In: "Log In",
        Help_Support: "Help & Support",
        Cancel: "Cancel",
        IDENTIFICATION: "IDENTIFICATION",
        ID_Sentences: "I identify myself at Swedbank och Sparbankerna",
        Security_Code: "Security Code",
        Identify: "Identify",
        I_identify_myself_at: "I identify myself at",
        Next: "Next",
        Welcome_to_CitiApp: "Welcome to",
        Track_your_matters: "Track your matters",
        It_is_those_feelings_that_drive___: "It is those feelings that drive our love of astronomy and our desire to learn more about it.",
        Get_to_know_your_city: "Get to know your city",
        Get_important_updates: "Get important updates",
        Account: "Account",
        Hi: "Hi",
        Today: "Today",
        Location: "Location",
        You_have_nothing_to_track_yet: "You have nothing to track yet.",
        Customize_your_dashboard: "Customize your dashboard",
        Home: "Home",
        Activity: "See & Do",
        Schedule: "Calendar",
        Matter: "My Pages",
        Basic_Info: "Basic Info",
        Notification_Settings: "Notification Settings",
        About_CitiApp: "About CitiApp",
        Logout: "Logout",
        My_Children: "My Children",
        Main_Menu: "Main Menu",
        Email_Address: "Email Address",
        Phone_Number: "Phone Number",
        Address: "Address",
        Edit: "Edit",
        Edit_Info: "Edit Info",
        Save: "Save",
        First_Name: "First Name",
        Last_Name: "Last Name",
        Street_Name: "Street Name",
        ZIP_Code: "ZIP Code",
        City: "City",
        Profile_Picture: "Profile Picture",
        Upload: "Upload",
        Notifications: "Notifications",
        Done: "Done",
        Search: "Search",
        Choose_how_can_we_help: "Choose how can we help",
        Report_follow_up: "Report follow up",
        Cases_issues: "Cases issues",
        Events_planning: "Events planning",
        Calendar_control: "Calendar control",
        Edit_account: "Edit account",
        Create_matters: "Create matters",
        FAQS: "FAQS",
        Contact_Us: "Contact Us",
        Title_of_page: "Title of page",
        Was_this_helpful: "Was the helpful?",
        Not_helpful: "Not helpful",
        It_helps: "It helps",
        So_helpful: "So helpful",
        Related_questions: "Related questions",
        My_Matters: "My Matters",
        Other_Matters: "Other Matters",
        Questions: "Questions",
        Error_Reports: "Error Reports",
        Suggestions: "Suggestions",
        Complinats: "Complinats",
        Case_Title: "Case Title",
        Case_Status: "Case Status",
        Case_Date: "Case Date",
        Required_Action: "Required Action",
        Ticket_ID: "Ticket ID",
        Ticket_Name: "Ticket Name",
        Category: "Category",
        Status: "Status",
        Date: "Date",
        All_cases: "All cases",
        Show_everything: "Show everything",
        School_issues: "School issues",
        Show_only_active_cases: "Show only active cases",
        Dental_issues: "Dental issues",
        Show_cases_that_has_a_result: "Show cases that has a result",
        In_Progress: "In Progress",
        Accepted: "Accepted",
        Created: "Created",
        Rejected: "Rejected",
        Completed: "Completed",
        Choose_what_to_track: "Choose what to track",
        Complete: "Complete",
        Waiting_Approval: "Waiting Approval",
        No_Action_Required: "No Action Required",
        Show_cases_that_require_approve_from_your_side: "Show cases that require approve from your side",
        Show_cases_that_require_no_action: "Show cases that require no action",
        Last_month: "Last month",
        Show_cases_within_the_last_month: "Show cases within the last month",
        Last_Three_Month: "Last Three Month",
        Show_cases_within_the_last_90days: "Show cases within the last 90 days",
        Case_Title: "Case Title",
        Creation_date: "Creation date",
        Approved: "Approved",
        Case_Title_up_to_two_lines: "Case Title up to two lines",
        Case_has_been_created_successfully: "Case has been created successfully",
        The_case_has_been_created________: "The case has been created, now the team will configure your case and start investigating, the moment the team starts, the case will become in progress.",
        Case_now_is_in_progress: "Case now is in progress",
        Your_case_was_rejected: "Your case was rejected",
        Your_case_was_approved: "Your case was approved",
        You_have_been_received_an_invite_for_a_meeting: "You have been received an invite for a meeting",
        Meeting_with_person_example: "Meeting with person example",
        Location_Place_or_tool: "Location Place or tool",
        Invitation_Details: "Invitation Details",
        Support_Agent: "Support Agent",
        Position_of_the_person: "Position of the person",
        With: "With",
        Complaint_ID: "Complaint ID",
        Details: "Details",
        Write_your_message: "Write your message...",
        Favorites: "Favorites",
        Coming_Soon: "Coming Soon",
        Outdoor_activities: "Outdoor activities",
        Swimming_Pools: "Swimming Pools",
        Books_Libraries: "Books Libraries",
        TRENDING: "TRENDING",
        See_All: "See All",
        NEAR_YOU: "NEAR YOU",
        OTHERS: "OTHERS",
        CLOSED: "CLOSED",
        OPEN: "OPEN",
        ALL_LIBRARIES: "ALL LIBRARIES",
        New_Coming: "New Coming",
        attendees: "attendees",
        interested: "interested",
        Tickets: "Tickets",
        Price_Range: "Price Range",
        Description: "Description",
        You_will_be_directed_to_a_third_party_app_to_book_the_event: "You will be directed to a third party app to book the event.",
        Book_Tickets: "Book Tickets",
        Add_to_Tider: "Add to Tider",
        Event_has_been_add_to_Tider: "Event has been add to Tider",
        In_Tider: "In Tider",
        You: 'You',
        Age_Restrictions: "Age Restrictions",
        Opening_Dates: "Opening Dates",
        age_value: "+18. No Childrens. Mix",
        Visit_Site: "Visit Site",
        All_Events: "All Events",
        All_Pools: "All Pools",
        Event_Details: "Event Details",
        Event_Site: "Event Site",
        Raise_a_Question: "Raise a Question",
        Add_Error_Report: "Add Error Report",
        Suggest_Something: "Suggest Something",
        Create_a_Complaint: "Create a Complaint",
        Remove_this_notification: "Remove this notification.",
        Stop_seeing_notification_about_this: "Stop seeing notification about this.",
        Customize_your_notifications: "Customize your notifications.",
        No_Error_reports_in_this_location: "No Error reports in this location",
        Be_the_first_to_raise_an_error___________: "Be this first to raise an error report in this area and help improve your city.",
        Raise: "Raise",
        Add_New: "Add New",
        Error_Details: "Error Details",
        People_notes: "People notes",
        empty_notes: "No one has add any notes to this report, if this is an issue you are facing you do not have to raise a new one, just add you own notes if needed.",
        Add_Note: "Add Note",
        New_Error_Report: "New Error Report",
        Error_report_title: "Error report title",
        Phone_Number_Optional: "Phone Number (Optional)",
        Location_is_by_default_is_yours: "Location is by default is yours",
        Up_to_three_images: "Up to three images",
        Drafts: "Drafts",
        Send: "Send",
        Save_as_draft: "Save as draft",
        View: "View",
        Thank_You: "Thank You",
        Error_report_has_been_successfully_____: "Error report has been successfully created.",
        Please_do_keep_the_tracking_ID_in_a_safe________: "Please do keep the tracking ID in a safe place in order for you to recall the case raised, thanks for helping us improve our city.",
        Your_complaint_has_been_successfully_added: "Your complaint has been successfully added.",
        Your_suggestion_has_been_successfully_added: "Your suggestion has been successfully added",
        Your_question_has_been_successfully_added: "Your question has been successfully added",
        Add_complaint: "Add complaint",
        Add_suggestion: "Add suggestion",
        Add_question: "Add question",
        Suggestion_title: "Suggestion title",
        Question_title: "Question title",
        Complaint_title: "Complaint title",
        Draft: "Draft",
        Add_Event: "Add Event",
        Calendar: "Calendar",
        Event_has_been_successfully_created: "Event has been successfully created",
        You_can_view_it_now_on_your_Calendar: "You can view it now on your Calendar",
        Create: "Create",
        Event_title: "Event Title",
        Add_Tag: "Add Tag",
        Guests: "Guests",
        Add_Video_Conference: "Add Video Conference",
        Tag: "Tag",
        Included_guests: "INCLUDED GUESTS",
        Enter_Location: "Enter Location",
        Invitation_is_related_to_the_case: "Invitation is related to the case",
        Reject: "Reject",
        Rejecting_invite: "Rejecting invite",
        Please_tell_us_why_you_would_like_to_reject_this____: "Please tell us why you would like to reject this invite?",
        Reason_example: 'Reason example',
        You_can_not_reject_an_invite_if_you_can__________: "You can not reject an invite if you can't write why you would like to do so.",
        Submit: "Submit",
        Invitations: "Invitations",
        Events: "Events",
        Change_Login_Method: "Change Login Method",
        LogIn_With_Email: "Log in with email",
        You_have_entered_incorrect_password: "You have entered incorrect password.",
        Email: "Email",
        Password: "Password",
        Forgot_Password: "Forgot Password?",
        Log_In: "Log In",
        Dont_you_have_an_account: "Don\'t you have an account?",
        Register_Now: "Register Now",
        Login_with_BankID_if_you_______: "Login with BankID if you want to access more services",
        Or: "Or",
        Forget_your_password: "Forget your password?",
        Dont_worry_just_fill_in_your_________: "Don\'t worry! Just fill in your email and we\'ll send you a link to reset your password.",
        Send_Email: "Send Email",
        Reset_Password: "Reset Password",
        Repeat_Password: "Repeat password",
        At_least_8_characters_____________: "At least 8 characters, at least one number.",
        Passwords_dont_match: "Passwords don\'t match",
        Change_Password: "Change Password",
        Thank_you_your_password_has_been_changed_successfully: "Thank you! Your password has been changed successfully.",
        Back_to_Citiapp: "Back to Citiapp",
        Add_your_email: "Add your email",
        registeration: "REGISTERATION",
        Create_my_account: "Create my account",
        Back_to_login: "Back to Login",
        We_have_sent_you_a_confirmation_email_please__________: "Your account is almost done, a link has been sent yo your email to activate your account and set your password",
        Set_new_password: "Set new password",
        Mobile_number: 'Mobile number',
        verify: 'Verify',
        e_g: "e.g 07x xxx xx",
        Thank_you_your_account_has_been_created_successfully: "You are all set now. \nYou can now login using your account info.",
        My_Information: "My Information",
        Languages: "Languages",
        Feedback: "Feedback",
        Rate_the_app: "Rate the app",
        Version10: "Version 1.0",
        Olivuex_ab: "\u00A9 OLIVUX AB",
        Svenska: "Svenska",
        English: "English",
        upload_an_image_or_screenshot: "upload an image or screenshot",
        Enter_your_feedback: "Enter your feedback",
        Give_feedback: "Give feedback",
        Clear: "Clear",
        Favortes: "Favortes",
        Pools_Lakes: "Pool & Lakes",
        Books_Libraries: "Books & Libraries",
        error_reports_in: "ERROR REPORTS IN ",
        saving: "Saving...",
        I_am_a_Guest: "I am a Guest",
        CitiApp_in_your_store: "CitiApp in your store",
        out_of: "out of",
        Rate_CitiApp: "Rate CitiApp",
        Draft_discarded: "Draft discarded",
        Undo: "UNDO",
        Where_is_it_happening: "Where is it happening?",
        current_location: "current location",
        recent: "recent",
        Add: 'Add',
        Alert: "Alert",
        News: "News",
        Login_with_BankID:"Login with Bank ID",
        Other_methods:"Other methods",
        No_worries_you_can_join_us_now_by____:"No worries, you can join us now by logging using your bank ID or any other method.",
        Sorry_only_members_____:"Sorry, only members are allowed to access.",
        Submit_Feedback:"Submit Feedback",
        Check_your_Email:"Check your Email",
        Why_do_we_ask_for_the_____:"Why do we ask for the Email address",
        In_order_to_make_sure_whether____________:"In order to make sure whether you have logged in before or not, we need to know if the email address is already registered in our database.",


    },
    "se": {
        CitiApp: "CitiApp",
        Sundsvalls_Kommun: "Kramfors Kommun",
        Log_In: "Log In",
        Help_Support: "Help & Support",
        Cancel: "Cancel",
        IDENTIFICATION: "IDENTIFICATION",
        ID_Sentences: "I identify myself at Swedbank och Sparbankerna",
        Security_Code: "Security Code",
        Identify: "Identify",
        I_identify_myself_at: "I identify myself at",
        Next: "Next",
        Welcome_to_CitiApp: "Welcome to",
        Track_your_matters: "Track your matters",
        It_is_those_feelings_that_drive___: "It is those feelings that drive our love of astronomy and our desire to learn more about it.",
        Get_to_know_your_city: "Get to know your city",
        Get_important_updates: "Get important updates",
        Account: "Account",
        Hi: "Hi",
        Today: "Today",
        Location: "Location",
        You_have_nothing_to_track_yet: "You have nothing to track yet.",
        Customize_your_dashboard: "Customize your dashboard",
        Home: "Home",
        Activity: "See & Do",
        Schedule: "Calendar",
        Matter: "My Pages",
        Basic_Info: "Basic Info",
        Notification_Settings: "Notification Settings",
        About_CitiApp: "About CitiApp",
        Logout: "Logout",
        My_Children: "My Children",
        Main_Menu: "Main Menu",
        Email_Address: "Email Address",
        Phone_Number: "Phone Number",
        Address: "Address",
        Edit: "Edit",
        Edit_Info: "Edit Info",
        Save: "Save",
        First_Name: "First Name",
        Last_Name: "Last Name",
        Street_Name: "Street Name",
        ZIP_Code: "ZIP Code",
        City: "City",
        Profile_Picture: "Profile Picture",
        Upload: "Upload",
        Notifications: "Notifications",
        Done: "Done",
        Search: "Search",
        Choose_how_can_we_help: "Choose how can we help",
        Report_follow_up: "Report follow up",
        Cases_issues: "Cases issues",
        Events_planning: "Events planning",
        Calendar_control: "Calendar control",
        Edit_account: "Edit account",
        Create_matters: "Create matters",
        FAQS: "FAQS",
        Contact_Us: "Contact Us",
        Title_of_page: "Title of page",
        Was_this_helpful: "Was the helpful?",
        Not_helpful: "Not helpful",
        It_helps: "It helps",
        So_helpful: "So helpful",
        Related_questions: "Related questions",
        My_Matters: "My Matters",
        Other_Matters: "Other Matters",
        Questions: "Questions",
        Error_Reports: "Error Reports",
        Suggestions: "Suggestions",
        Complinats: "Complinats",
        Case_Title: "Case Title",
        Case_Status: "Case Status",
        Case_Date: "Case Date",
        Required_Action: "Required Action",
        Ticket_ID: "Ticket ID",
        Ticket_Name: "Ticket Name",
        Category: "Category",
        Status: "Status",
        Date: "Date",
        All_cases: "All cases",
        Show_everything: "Show everything",
        School_issues: "School issues",
        Show_only_active_cases: "Show only active cases",
        Dental_issues: "Dental issues",
        Show_cases_that_has_a_result: "Show cases that has a result",
        In_Progress: "In Progress",
        Accepted: "Accepted",
        Created: "Created",
        Rejected: "Rejected",
        Completed: "Completed",
        Waiting_Approval: "Waiting Approval",
        No_Action_Required: "No Action Required",
        Show_cases_that_require_approve_from_your_side: "Show cases that require approve from your side",
        Show_cases_that_require_no_action: "Show cases that require no action",
        Last_month: "Last month",
        Show_cases_within_the_last_month: "Show cases within the last month",
        Last_Three_Month: "Last Three Month",
        Show_cases_within_the_last_90days: "Show cases within the last 90 days",
        Case_Title: "Case Title",
        Creation_date: "Creation date",
        Approved: "Approved",
        Case_Title_up_to_two_lines: "Case Title up to two lines",
        Case_has_been_created_successfully: "Case has been created successfully",
        The_case_has_been_created________: "The case has been created, now the team will configure your case and start investigating, the moment the team starts, the case will become in progress.",
        Case_now_is_in_progress: "Case now is in progress",
        Your_case_was_rejected: "Your case was rejected",
        Your_case_was_approved: "Your case was approved",
        You_have_been_received_an_invite_for_a_meeting: "You have been received an invite for a meeting",
        Meeting_with_person_example: "Meeting with person example",
        Location_Place_or_tool: "Location Place or tool",
        Invitation_Details: "Invitation Details",
        Support_Agent: "Support Agent",
        Position_of_the_person: "Position of the person",
        With: "With",
        Complaint_ID: "Complaint ID",
        Details: "Details",
        Write_your_message: "Write your message...",
        Favorites: "Favorites",
        Coming_Soon: "Coming Soon",
        Outdoor_activities: "Outdoor activities",
        Swimming_Pools: "Swimming Pools",
        Books_Libraries: "Books Libraries",
        TRENDING: "TRENDING",
        See_All: "See All",
        NEAR_YOU: "NEAR YOU",
        OTHERS: "OTHERS",
        CLOSED: "CLOSED",
        OPEN: "OPEN",
        ALL_LIBRARIES: "ALL LIBRARIES",
        New_Coming: "New Coming",
        attendees: "attendees",
        interested: "interested",
        Tickets: "Tickets",
        Price_Range: "Price Range",
        Description: "Description",
        You_will_be_directed_to_a_third_party_app_to_book_the_event: "You will be directed to a third party app to book the event.",
        Book_Tickets: "Book Tickets",
        Add_to_Tider: "Add to Tider",
        Event_has_been_add_to_Tider: "Event has been add to Tider",
        In_Tider: "In Tider",
        You: 'You',
        Age_Restrictions: "Age Restrictions",
        Opening_Dates: "Opening Dates",
        age_value: "+18. No Childrens. Mix",
        Visit_Site: "Visit Site",
        All_Events: "All Events",
        All_Pools: "All Pools",
        Event_Details: "Event Details",
        Event_Site: "Event Site",
        Raise_a_Question: "Raise a Question",
        Add_Error_Report: "Add Error Report",
        Suggest_Something: "Suggest Something",
        Create_a_Complaint: "Create a Complaint",
        Remove_this_notification: "Remove this notification.",
        Stop_seeing_notification_about_this: "Stop seeing notification about this.",
        Customize_your_notifications: "Customize your notifications.",
        No_Error_reports_in_this_location: "No Error reports in this location",
        Be_the_first_to_raise_an_error___________: "Be this first to raise an error report in this area and help improve your city.",
        Raise: "Raise",
        Add_New: "Add New",
        Error_Details: "Error Details",
        People_notes: "People notes",
        empty_notes: "No one has add any notes to this report, if this is an issue you are facing you do not have to raise a new one, just add you own notes if needed.",
        Add_Note: "Add Note",
        New_Error_Report: "New Error Report",
        Error_report_title: "Error report title",
        Phone_Number_Optional: "Phone Number (Optional)",
        Location_is_by_default_is_yours: "Location is by default is yours",
        Up_to_three_images: "Up to three images",
        Drafts: "Drafts",
        Send: "Send",
        Save_as_draft: "Save as draft",
        View: "View",
        Thank_You: "Thank You",
        Error_report_has_been_successfully_____: "Error report has been successfully created.",
        Please_do_keep_the_tracking_ID_in_a_safe________: "Please do keep the tracking ID in a safe place in order for you to recall the case raised, thanks for helping us improve our city.",
        Your_complaint_has_been_successfully_added: "Your complaint has been successfully added.",
        Your_suggestion_has_been_successfully_added: "Your suggestion has been successfully added",
        Your_question_has_been_successfully_added: "Your question has been successfully added",
        Add_complaint: "Add complaint",
        Add_suggestion: "Add suggestion",
        Add_question: "Add question",
        Suggestion_title: "Suggestion title",
        Question_title: "Question title",
        Complaint_title: "Complaint title",
        Draft: "Draft",
        Add_Event: "Add Event",
        Calendar: "Calendar",
        Event_has_been_successfully_created: "Event has been successfully created",
        You_can_view_it_now_on_your_Calendar: "You can view it now on your Calendar",
        Create: "Create",
        Event_title: "Event Title",
        Add_Tag: "Add Tag",
        Guests: "Guests",
        Add_Video_Conference: "Add Video Conference",
        Tag: "Tag",
        Included_guests: "INCLUDED GUESTS",
        Enter_Location: "Enter Location",
        Invitation_is_related_to_the_case: "Invitation is related to the case",
        Reject: "Reject",
        Rejecting_invite: "Rejecting invite",
        Please_tell_us_why_you_would_like_to_reject_this____: "Please tell us why you would like to reject this invite?",
        Reason_example: 'Reason example',
        You_can_not_reject_an_invite_if_you_can__________: "You can not reject an invite if you can't write why you would like to do so.",
        Submit: "Submit",
        Invitations: "Invitations",
        Events: "Events",
        Change_Login_Method: "Change Login Method",
        LogIn_With_Email: "Log in with email",
        You_have_entered_incorrect_password: "You have entered incorrect password.",
        Email: "Email",
        Password: "Password",
        Forgot_Password: "Forgot_Password?",
        Log_In: "Log In",
        Dont_you_have_an_account: "Don\'t you have an account?",
        Register_Now: "Register Now",
        Login_with_BankID_if_you_______: "Login with BankID if you want to access more services",
        Or: "Or",
        Forget_your_password: "Forget your password?",
        Dont_worry_just_fill_in_your_________: "Don\'t worry! Just fill in your email and we\'ll send you a link to reset your password.",
        Send_Email: "Send Email",
        Reset_Password: "Reset Password",
        Repeat_Password: "Repeat password",
        At_least_8_characters_____________: "At least 8 characters, at least one number.",
        Passwords_dont_match: "Passwords don\'t match",
        Change_Password: "Change Password",
        Thank_you_your_password_has_been_changed_successfully: "Thank you! Your password has been changed successfully.",
        Back_to_Citiapp: "Back to Citiapp",
        Add_your_email: "Add your email",
        registeration: "REGISTERATION",
        Create_my_account: "Create my account",
        Back_to_login: "Back to Login",
        We_have_sent_you_a_confirmation_email_please__________: "Your account is almost done, a link has been sent yo your email to activate your account and set your password",
        Set_new_password: "Set new password",
        Mobile_number: 'Mobile number',
        verify: 'Verify',
        e_g: "e.g 07x xxx xx",
        Thank_you_your_account_has_been_created_successfully: "You are all set now. You can now login using your account info.",
        My_Information: "My Information",
        Languages: "Languages",
        Feedback: "Feedback",
        Rate_the_app: "Rate the app",
        Version10: "Version 1.0",
        Olivuex_ab: "\u00A9 OLIVUX AB",
        Svenska: "Svenska",
        English: "English",
        upload_an_image_or_screenshot: "upload an image or screenshot",
        Enter_your_feedback: "Enter your feedback",
        Give_feedback: "Give feedback",
        Clear: "Clear",
        Favortes: "Favortes",
        Pools_Lakes: "Pool & Lakes",
        Books_Libraries: "Books & Libraries",
        error_reports_in: "ERROR REPORTS IN ",
        saving: "Saving...",
        I_am_a_Guest: "I am a Guest",
        CitiApp_in_your_store: "CitiApp in your store",
        out_of: "out of",
        Rate_CitiApp: "Rate CitiApp",
    },
});
export default strings;