require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'CitiApp0630' do

  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path 
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'

  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])
  

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNI18n', :path => '../node_modules/react-native-i18n'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  # pod 'react-native-image-crop-picker', :path => '../node_modules/react-native-image-crop-picker/ios'


  pod 'react-native-text-input-mask', :path => '../node_modules/react-native-text-input-mask'

  target 'CitiApp0630Tests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'CitiApp0630-tvOS' do
  # Pods for CitiApp0630-tvOS

  target 'CitiApp0630-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
