import { StyleSheet } from 'react-native'
import { Metrics, ApplicationStyles, Colors, Fonts } from '../../Themes/'
import { calcHeight, calcWidth, deviceHeight, deviceWidth } from '../../Themes/ConvertSize'
export default StyleSheet.create({
  ...ApplicationStyles.screen,
  container: {
    paddingBottom: Metrics.baseMargin
  },
  mainContainer: {
    backgroundColor: Colors.white,
  },
  section: {
    alignItems: 'center',
  },
  backgroundImage: {
    width: deviceWidth,
    height: calcHeight(487),
    resizeMode: 'stretch',
  },
  sectionTitle: {
    fontSize: Fonts.size.h3,
    fontWeight: 'bold',
    lineHeight: calcHeight(48),
    color: Colors.black,
    letterSpacing: 0.36,
    fontFamily: Fonts.type.base,
  },
  titleText: {
    fontSize: Fonts.size.spec,
    lineHeight: calcHeight(22),
    color: Colors.black,
    letterSpacing: 0.36,
    fontFamily: Fonts.type.base,
    fontWeight: '500',
  },
  titleimage:{
    width:calcHeight(20),
    height:calcHeight(20),
    resizeMode:'contain',
  },
  buttongroup: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: calcWidth(331),
  },
  edit_info: {
    fontSize: Fonts.size.spec,
    fontWeight: '500',
    lineHeight: calcHeight(22),
    color: Colors.black,
    letterSpacing: 0.36,
    fontFamily: Fonts.type.base,
  },
  cancel: {
    fontSize: Fonts.size.medium,
    fontWeight: '500',
    lineHeight: calcHeight(22),
    color: Colors.primary,
    letterSpacing: 0.36,
    fontFamily: Fonts.type.base,
  },
  sectionone: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: calcHeight(15),
    width: calcWidth(335),
    borderWidth: calcHeight(1),
    borderRadius: calcHeight(5),
    borderColor: Colors.gray3,
  },
  leftpart: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  imageitem: {
    width: calcHeight(50),
    height: calcHeight(50),
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.gray5,
    borderRadius: calcHeight(5),
  },
  usericon: {
    width: calcHeight(25),
    height: calcHeight(25),
    resizeMode: 'contain',
    tintColor: Colors.white,
  },
  profile: {
    fontSize: Fonts.size.medium,
    fontWeight: '500',
    lineHeight: calcHeight(21),
    color: Colors.gray3,
    letterSpacing: 0.36,
    fontFamily: Fonts.type.base,
    marginLeft: calcHeight(16),
  },
  setiontwo: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: calcWidth(335),
  },
  title: {
    fontSize: Fonts.size.regular,
    lineHeight: calcHeight(24),
    color: Colors.black2,
    letterSpacing: 0.374,
    fontFamily: Fonts.type.base,
    fontWeight: '600',
    width: calcWidth(335),
  },
  itemcontainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: calcWidth(335),
    marginTop: calcHeight(16),
  },
  faqlabel: {
    fontSize: Fonts.size.medium,
    fontWeight: '500',
    lineHeight: calcHeight(21),
    color: Colors.gray1,
    letterSpacing: 0.374,
    fontFamily: Fonts.type.base,
    width: calcWidth(335),
  },
  faqtitle: {
    fontSize: Fonts.size.h5,
    fontWeight: '500',
    lineHeight: calcHeight(29),
    color: Colors.black0,
    letterSpacing: 0.374,
    fontFamily: Fonts.type.base,
    width: calcWidth(335),
  },
  faqtext: {
    fontSize: Fonts.size.medium,
    fontWeight: '500',
    lineHeight: calcHeight(21),
    color: Colors.black3,
    letterSpacing: 0.374,
    fontFamily: Fonts.type.base,
    width: calcWidth(335),
  },
  feedback: {
    fontSize: Fonts.size.small,
    lineHeight: calcHeight(18),
    color: Colors.black3,
    letterSpacing: 0.374,
    fontFamily: Fonts.type.base,
    width: calcWidth(335),
    marginTop: calcHeight(15),
  },
  hidefeedback: {
    fontSize: Fonts.size.small,
    lineHeight: calcHeight(18),
    color: Colors.black3,
    letterSpacing: 0.374,
    fontFamily: Fonts.type.base,
    width: calcWidth(335),
    marginTop: calcHeight(15),
    display: 'none',
  },
  topcontainer:{
    width:calcWidth(335),
    alignSelf:'center',
  }
})
