import { StyleSheet } from 'react-native'
import { Metrics, ApplicationStyles, Colors, Fonts } from '../../Themes/'
import { calcHeight, calcWidth, deviceHeight, deviceWidth } from '../../Themes/ConvertSize'
export default StyleSheet.create({
  ...ApplicationStyles.screen,
  container: {
    paddingBottom: Metrics.baseMargin
  },
  mainContainer: {
    backgroundColor: Colors.black,
  },
  layout: {
    backgroundColor: Colors.gray0,
    height: calcHeight(15),
    marginTop: calcHeight(40),
    borderTopRightRadius: calcHeight(60),
    borderTopLeftRadius: calcHeight(60),
    marginHorizontal: calcHeight(25),
  },
  section: {
    backgroundColor: Colors.white,
    borderTopLeftRadius: calcHeight(15),
    borderTopRightRadius: calcHeight(15),
    alignItems: 'center',
  },
  backgroundImage: {
    width: deviceWidth,
    height: calcHeight(487),
    resizeMode: 'stretch',
  },
  sectionTitle: {
    fontSize: Fonts.size.h3,
    fontWeight: 'bold',
    lineHeight: calcHeight(48),
    color: Colors.black,
    letterSpacing: 0.36,
    fontFamily: Fonts.type.base,
  },
  titleText: {
    fontSize: Fonts.size.h4,
    lineHeight: calcHeight(42),
    color: Colors.black,
    letterSpacing: 0.36,
    fontFamily: Fonts.type.base,
    marginLeft: calcHeight(5),
    textAlign: 'center',
    fontWeight: 'bold',
    width: calcHeight(200),
  },
  buttongroup: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    width: calcWidth(331),
  },
  edit_info: {
    fontSize: Fonts.size.spec,
    fontWeight: '500',
    lineHeight: calcHeight(22),
    color: Colors.black,
    letterSpacing: 0.36,
    fontFamily: Fonts.type.base,
  },
  cancel: {
    fontSize: Fonts.size.medium,
    fontWeight: '500',
    lineHeight: calcHeight(22),
    color: Colors.primary,
    letterSpacing: 0.36,
    fontFamily: Fonts.type.base,
  },
  sectionone: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: calcHeight(15),
    width: calcWidth(335),
    borderWidth: calcHeight(1),
    borderRadius: calcHeight(5),
    borderColor: Colors.gray3,
  },
  leftpart: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  imageitem: {
    width: calcHeight(50),
    height: calcHeight(50),
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.gray5,
    borderRadius: calcHeight(5),
  },
  usericon: {
    width: calcHeight(25),
    height: calcHeight(25),
    resizeMode: 'contain',
    tintColor: Colors.white,
  },
  profile:{
    fontSize: Fonts.size.medium,
    fontWeight: '500',
    lineHeight: calcHeight(21),
    color: Colors.gray3,
    letterSpacing: 0.36,
    fontFamily: Fonts.type.base,
    marginLeft:calcHeight(16),
  },
  setiontwo:{
    flexDirection:'row',
    justifyContent:'space-between',
    alignItems:'center',
    width:calcWidth(335),
  },
  title: {
    fontSize: Fonts.size.h9,
    lineHeight: calcHeight(41),
    color: Colors.black,
    letterSpacing: 0.374,
    fontFamily: Fonts.type.base,
    fontWeight: 'bold',
    marginTop:calcHeight(50),
  },
  itemcontainer:{
    flexDirection:'row',
    alignItems:'center',
    justifyContent:'space-between',
    width:calcWidth(335),
    marginTop:calcHeight(16),
  },
  completebutton:{
    backgroundColor:Colors.primary,
    alignItems:'center',
    justifyContent:'center',
    width:calcWidth(261),
    height:calcHeight(40),
    borderRadius:calcHeight(5),
  },
  completetext:{
    fontSize:Fonts.size.spec,
    color:Colors.white,
    fontWeight:'600',
    lineHeight:calcHeight(22),
    letterSpacing:-0.408
  },
})
