import {StyleSheet} from 'react-native';
import {
  Metrics,
  ApplicationStyles,
  Colors,
  Fonts,
  DummyData,
} from '../../Themes/';
import {
  calcHeight,
  calcWidth,
  deviceHeight,
  deviceWidth,
} from '../../Themes/ConvertSize';
export default StyleSheet.create({
  ...ApplicationStyles.screen,
  container: {
    paddingBottom: Metrics.baseMargin,
  },
  mainContainer: {
    flex: 1,
  },
  titleText: {
    fontSize: Fonts.size.h4,
    color: Colors.black,
    fontFamily: Fonts.type.base,
    fontWeight: 'bold',
  },
  titleText1: {
    fontSize: Fonts.size.medium,
    color: Colors.gray1,
    fontFamily: Fonts.type.base,
    fontWeight: 'bold',
  },
  bluebutton: {
    width: calcWidth(93),
    height: calcHeight(33),
    borderRadius: calcHeight(4),
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.midblue,
  },
  scrollcontainer: {
    width: calcWidth(343),
    alignSelf: 'center',
    height: calcHeight(265),
  },
  scrollcontainer1: {
    width: calcWidth(343),
    alignSelf: 'center',
    height: calcHeight(500),
  },
  searchcontainer: {
    alignItems: 'center',
    width: deviceWidth,
  },
  modal: {
    alignItems: 'center',
    width: calcWidth(317),
    height: calcHeight(373),
    borderRadius: calcHeight(6),
    justifyContent: 'center',
  },
  modal_text: {
    fontSize: Fonts.size.medium,
    color: Colors.gray1,
    fontFamily: Fonts.type.base,
    fontWeight: 'normal',
    width: calcWidth(253),
  },
  modal_title: {
    fontSize: Fonts.size.input,
    color: Colors.black,
    fontFamily: Fonts.type.base,
    fontWeight: 'bold',
    width: calcWidth(253),
  },
  buttonview: {},
  viewimage: {
    width: calcWidth(38),
    height: calcHeight(8),
    borderRadius: calcHeight(2),
    backgroundColor: Colors.gray8,
  },
  title: {
    fontSize: Fonts.size.h5,
    color: Colors.black7,
    fontFamily: Fonts.type.base,
    fontWeight: '600',
  },
  headersection: {
    flexDirection: 'row',
    width: calcWidth(331),
    alignSelf: 'center',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
  },
  headertext: {
    fontSize: Fonts.size.medium,
    color: Colors.primary,
    fontFamily: Fonts.type.base,
    fontWeight: '600',
    lineHeight: calcHeight(21),
    letterSpacing: 0.374,
  },
  horscrollcontainer: {
    width: calcWidth(331),
    alignSelf: 'center',
  },
  invitation_label: {
    fontSize: Fonts.size.medium,
    color: Colors.black4,
    fontFamily: Fonts.type.base,
    fontWeight: '600',
    lineHeight: calcHeight(21),
    letterSpacing: 0.374,
    width: calcWidth(331),
    alignSelf: 'center',
  },
  displaytoday: {
    width: calcWidth(331),
    alignSelf: 'center',
  },
  todaylabel: {
    fontSize: Fonts.size.medium,
    color: Colors.black4,
    fontFamily: Fonts.type.base,
    fontWeight: '600',
    lineHeight: calcHeight(21),
    letterSpacing: 0.374,
  },
  todayevents: {
    fontSize: Fonts.size.small,
    color: Colors.gray6,
    fontFamily: Fonts.type.base,
    fontWeight: '600',
    lineHeight: calcHeight(21),
    letterSpacing: 0.374,
  },
  grayline: {
    width: calcWidth(331),
    backgroundColor: Colors.gray1,
    height: calcHeight(1),
    alignSelf: 'center',
  },
  modaltop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: calcWidth(253),
    alignItems: 'center',
  },
  modal_calendar: {
    width: calcHeight(45),
    height: calcHeight(45),
    resizeMode: 'contain',
  },
  modal_close: {
    width: calcHeight(31),
    height: calcHeight(31),
    resizeMode: 'contain',
    borderRadius: calcHeight(31 / 2),
  },
  horweekcontainer: {
    width: calcWidth(331),
    alignSelf: 'center',
  },
  titleweek: {
    fontSize: Fonts.size.medium,
    color: Colors.black,
    fontFamily: Fonts.type.base,
    fontWeight: '600',
    lineHeight: calcHeight(21),
    letterSpacing: 0.374,
    width: calcWidth(331),
    alignSelf: 'center',
    marginVertical: calcHeight(11),
  },
  weekitem: {
    width: calcWidth(49),
  },
  dotteditem: {
    width: calcHeight(4),
    height: calcHeight(4),
    borderRadius: calcHeight(4) / 2,
    marginHorizontal: calcWidth(1),
  },
  dottedtemcontent: {
    flexDirection: 'row',
    height: calcHeight(5),
    justifyContent: 'center',
    alignItems: 'center',
  },
  dottedbutton: {
    alignItems: 'center',
    width: calcWidth(49),
    borderBottomColor: Colors.primary,
    borderBottomWidth: calcHeight(3),
  },
  dottedbottombutton: {
    marginTop: calcHeight(6),
    marginBottom: calcHeight(10),
    fontSize: Fonts.size.tt,
    color: Colors.black14,
    fontFamily: Fonts.type.base,
    fontWeight: 'bold',
    lineHeight: calcHeight(18),
    letterSpacing: -0.078,
  },
  dottedtopbutton: {
    marginBottom: calcHeight(3),
    fontSize: Fonts.size.tt,
    color: Colors.gray6,
    fontFamily: Fonts.type.base,
    fontWeight: 'bold',
    lineHeight: calcHeight(18),
    letterSpacing: -0.078,
  },
  bottomeventscontainer: {
    width: calcWidth(341),
    alignSelf: 'center',
    paddingTop: calcHeight(14),
  },
  lefttimecontainer: {
    width: calcWidth(36),
    alignItems: 'flex-end',
  },
  righttimecontainer: {
    width: calcWidth(290),
    alignSelf:'center',
  },
  eventcontent: {
    width: calcWidth(341),
    flexDirection: 'row',
    justifyContent: 'center',
    marginVertical:calcHeight(10)
  },
  timeitemlabel: {
    marginBottom: calcHeight(28),
    fontSize: Fonts.size.small,
    color: Colors.gray6,
    fontFamily: Fonts.type.base,
    lineHeight: calcHeight(18),
    letterSpacing: -0.078,
  },
  eventdetailcontent: {
    borderRadius: calcHeight(10),
    backgroundColor: Colors.white,
    borderLeftWidth: calcWidth(4),
    paddingLeft: calcWidth(16),
    paddingVertical:calcHeight(14),
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.8,
    shadowRadius: 1,
    elevation: 5,
  },
  noeventlin: {
    marginTop:calcHeight(5),
    width: calcWidth(290),
    justifyContent: 'flex-end',
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom:calcHeight(32)
  },
  dotlinedot: {
    width: calcHeight(9),
    height: calcHeight(9),
    borderRadius: calcHeight(9 / 2),
    backgroundColor: Colors.weightblue,
  },
  linedotline: {
    width: calcHeight(350),
    height: calcHeight(1),
    backgroundColor: Colors.weightblue,
  },
  titleitemm:{
    fontSize: Fonts.size.medium,
    color: Colors.lightgreen,
    fontFamily: Fonts.type.base,
    fontWeight: '600',
    lineHeight: calcHeight(21),
    letterSpacing: 0.374,
  },
  timeitemm:{
    fontSize: Fonts.size.small,
    color: Colors.charcoal,
    fontFamily: Fonts.type.base,
    fontWeight: '500',
    lineHeight: calcHeight(18),
    letterSpacing: 0.374,
  },
  locationitemm:{
    fontSize: Fonts.size.small,
    color: Colors.charcoal,
    fontFamily: Fonts.type.base,
    lineHeight: calcHeight(18),
    letterSpacing: 0.374,
    marginTop:calcHeight(25)
  },
  inviteesitemm:{
    fontSize: Fonts.size.small,
    color: Colors.charcoal,
    fontFamily: Fonts.type.base,
    lineHeight: calcHeight(18),
    letterSpacing: 0.374,
    marginTop:calcHeight(2)
  }
});
